// svelte-frontend/src/components/content/Word.svelte
<script lang='ts'>
    
    export let text: string;
    export let onSelectionChange: Function;

    const hanldeOnChange = (event: MouseEvent) => {
        event.preventDefault();
    }

</script>

<span 
    class="leading-loose hover:text-red-500"
    on:click={onSelectionChange}
>
    {text}
</span>

// frontend/pages/word.tsx
import React, { MouseEvent } from 'react';
import { useState } from 'react';

type WordProps = {
    index: number;
    text: string;
    onSelectionChange: Function;
}

function Word( { index, text, onSelectionChange} : WordProps) {
    const [color, setColor] = useState('red');
    const [clickCounter, setClickCounter] = useState(0);

    const hanldeOnChange = (event: MouseEvent) => {
        event.preventDefault();
        setColor(color === 'red' ?'yellow': 'red');
        setClickCounter(clickCounter + 1);
        console.log({index});
        onSelectionChange(index);
    }

    return <div onClick={hanldeOnChange} >
        { text }
        &nbsp;
        <br />

    </div>;
}

export default Word;
